[project]
name = "bitrex"
description = "Bitcoin Dual-Yield Optimizer on Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.sip010-trait]
path = "contracts/traits/sip010-trait.clar"

[contracts.strategy-trait]
path = "contracts/traits/strategy-trait.clar"

[contracts.bitrex-vault]
path = "contracts/bitrex-vault.clar"

[contracts.bitrex-strategy-router]
path = "contracts/bitrex-strategy-router.clar"

[contracts.adapter-zest]
path = "contracts/adapters/adapter-zest.clar"

[contracts.adapter-bitflow]
path = "contracts/adapters/adapter-bitflow.clar"

[contracts.adapter-stacking]
path = "contracts/adapters/adapter-stacking.clar"

[contracts.fee-manager]
path = "contracts/fee-manager.clar"

[repl]
costs_version = 3
parser_version = 2
